# Generated by Django 3.2.6 on 2021-08-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videos_id', models.SlugField(max_length=11, primary_key=True, serialize=False)),
                ('videos_title', models.TextField(max_length=100)),
                ('videos_description', models.TextField(max_length=5000)),
                ('videos_count_original', models.BigIntegerField(default=0)),
                ('videos_count_sited', models.BigIntegerField(default=0)),
                ('videos_lastupdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
