# Generated by Django 3.2.6 on 2021-08-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtrees', '0003_auto_20210822_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='children_video_child',
        ),
        migrations.AddField(
            model_name='children',
            name='children_video_child',
            field=models.ForeignKey(default='jNQXAC9IVRw', on_delete=django.db.models.deletion.CASCADE, related_name='child_table', to='vtrees.videos_info'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='children',
            name='children_video_parent',
        ),
        migrations.AddField(
            model_name='children',
            name='children_video_parent',
            field=models.SlugField(default='jNQXAC9IVRw', max_length=11),
            preserve_default=False,
        ),
    ]
